### ISSUE TITLE
Error when downloading atlases 

### ISSUE THREAD

**Issue by nikitas-theo** [Parietal-INRIA/MODL_atlas#16]
It appears there is some problem in nilearn.utils._fetch_files .
I include the error message,
`    files = _fetch_files(data_dir, files, verbose=2)
  File "/home/semeval/anaconda3/lib/python3.7/site-packages/nilearn/datasets/utils.py", line 721, in _fetch_files
    verbose=verbose, session=session)
  File "/home/semeval/anaconda3/lib/python3.7/site-packages/nilearn/datasets/utils.py", line 797, in _fetch_files
    raise IOError('Fetching aborted: ' + abort)
OSError: Fetching aborted: Dataset has been downloaded but requested file was not provided:
URL: https://osf.io/3vrct/download
Target file: /home/semeval/nilearn_data/difumo_atlases/256/maps.nii.gz
Downloaded: /home/semeval/nilearn_data/difumo_atlases/d7aa641714f90074ed0175b5ebcb43b8/download`

**Comment by KamalakerDadi** [comment]
Hi,
Thank you for raising an issue. It is fixed now. Please let me know if issue still exists.

**Comment by KamalakerDadi** [comment]
Sorry for the noise.

**Comment by nikitas-theo** [comment]
Thank you for fixing it ASAP. Can i quickly ask another question, although it is not issue related. Resampling maps in a dataset of  shape=(53, 63, 52, 857) seems to take forever. Is this computationally intractable or is there a problem with my system?

**Comment by bthirion** [comment]
It depends on whether the transformation is a pure translation (in which case it should be fast) or not (-> trilinear interpolation is then used, which is more costly).

**Comment by nikitas-theo** [comment]
Thank you for the reply, I am sorry it is actually the `[NiftiMapsMasker.transform_single_imgs] Extracting region signals
` step that seems to be stuck

**Comment by KamalakerDadi** [comment]
>it is actually the [NiftiMapsMasker.transform_single_imgs] Extracting region signals step that seems to be stuck

I assume you are using default resampling strategy i.e., resampling functional data to maps. Is this the step that is stuck?

**Comment by nikitas-theo** [comment]
I am using default settings. I am posting the terminal output, the step "Extracting region signals" never finishes. 
```
[NiftiMapsMasker.fit_transform] loading regions from /home/semeval/nilearn_data/difumo_atlases/1024/2mm/maps.nii.gz
Resampling maps
[NiftiMapsMasker.transform_single_imgs] Loading data from Nifti1Image(
shape=(53, 63, 52, 857),
affine=array([[  -3.,    0.,    0.,   78.],
       [   0.,    3.,    0., -112.],
       [   0.,    0.,    3.,  -70.],
       [   0.,    0.,    0.,    1.]])
)
[NiftiMapsMasker.transform_single_imgs] Extracting region signals

```

**Comment by bthirion** [comment]
@KamalakerDadi IIRC there is a 3mm-version of the Difumo atlas. using it instead does bypass the resampling step. Am I right ?

**Comment by KamalakerDadi** [comment]
>@KamalakerDadi IIRC there is a 3mm-version of the Difumo atlas. using it instead does bypass the resampling step. Am I right?

I don't think so unless ```resampling_target=None```.
We can resample mask, functional data to maps resolution using ```resample_img``` before using NiftiMapsMasker, then simply putting ```resampling_target=None``` in NiftiMapsMasker may avoid this issue.

That's one way or try maps resolution to 3mm.

**Comment by KamalakerDadi** [comment]
@nikitas-theo i assume its ok
