### ISSUE TITLE
Dimension of DiFuMo is not consistent with MNI

### ISSUE THREAD

**Issue by yusaiwen** [Parietal-INRIA/MODL_atlas#18]
Hi!

I am trying to extract values of ROI defined by DiFuMo, but I found the dimension of DiFuMo and MNI152NLin2009cAsym is not the same(see blew).
<img width="587" alt="image" src="https://user-images.githubusercontent.com/21970068/157016268-b98538fa-acb6-4ebe-962f-5804f1372a42.png">

So when I used fslsplit to split the 4D image to 3D images and then binaried them to a mask for ROI and finally calculated the cluster size under the ROI, error occurred:
<img width="696" alt="image" src="https://user-images.githubusercontent.com/21970068/157016789-3b405405-d982-4db9-8d8f-08b6c5de149f.png">

Many thanks,
Saiwen Yu

**Comment by bthirion** [comment]
What you need to do is to resample Difumo images to the MNI template image. You can use e.g. 
https://nilearn.github.io/modules/generated/nilearn.image.resample_to_img.html

**Comment by yusaiwen** [comment]
Thanks a lot.
