### ISSUE TITLE
A ventricle, rather than a Thalamic radiation?

### ISSUE THREAD

**Issue by GaelVaroquaux** [Parietal-INRIA/MODL_atlas#6]
The following component is a ventricle, isn't it?
https://parietal-inria.github.io/DiFuMo/1024/html/565.html

Should it be named as a ventricle?

**Comment by antonia-ms** [comment]
Yes. 565 should be changed to 'Lateral ventricles posterior' and 800 to 'Fornix antero-superior'. Thanks for the catch.
